### ISSUE TITLE
Figure mislabeling in the output .png files

### ISSUE THREAD

**Issue by earosenthal** [ryanlayer/samplot#121]
I am including three bamfiles in my command. Unless I include the <-t SV_TYPE> flag, the labels on the figures are out of order. For example, when I use the command 'samplot -n 430477-M 430478-D 430479-P  -b $MOMBAM $DADBAM $PROBAM -o trial-01.png -c 7 -s 70252194 -e 70598026', the figures are in the order of mom, dad, proband from top to bottom. However, the labeling on the figures is in the order proband, mom, dad from top to bottom.
My computing environment is Linux/CentOS7/x86_64. using the following versions: python/3.7.7, numpy/1.19.2, matplotlib/3.2.1, pysam/0.16.0.1 and samplot/1.0.1.

Please let me know if you have any questions or suggestions, and thanks for your time.

**Comment by jbelyeu** [comment]
This is fixed in samplot >= 1.0.18. Notice that the command for running samplot has also changed slightly (documented in readme). I recommend installing from conda but if you prefer to install manually from the releases page, the newest release should also solve your problem. Let us know if the issue persists, of course.
