### ISSUE TITLE
Question about interpreting the plots

### ISSUE THREAD

**Issue by davidecarlson** [ryanlayer/samplot#137]
Hi All,
Thanks for this excellent tool.  It's really helping me make sense of my SV calls.  I have a question about some of the reads that are showing up as "duplications" in samples without a called SV.  For example:

![image](https://user-images.githubusercontent.com/25590156/116424950-ed0d9c00-a80f-11eb-9391-1f11f61e45fc.png)

This is a deletion SV, but the bottom sample (which has the  reference genotype) has several reads in red marked as duplications.  Are these simply PE reads that have -/+ orientation (instead of the expected +/-)?  Or is there some other meaning behind these reads getting the duplication label?  
Thanks for your help!
Dave

**Comment by jbelyeu** [comment]
That's right, there are lots in reads in some regions of the genome with a -/+ orientation. It's also not unusual to see reads that could indicate other SVs due to inaccurate mapping. Samplot minimizes bias by simply showing these reads and allowing the user to decide if they're meaningful, while downsampling normal (concordant) reads to simplify the image. In this case I'd say that the 500bp deletion appears to be homozygous in the top sample, heterozygous in the second, and absent from each control. It does appear that something could be going on with the bottom sample though - not a clear sign of duplications but I do see some small deletions in addition to the random DUP reads you've pointed out. Maybe some minor sequencing issue?

To be clear, the meaning behind the legend is that what a read _indicates_, and should never be taken at face value with a single read. A pile-up of reads such as is seen with the top two samples is what I look for. 

Hope that helps!

**Comment by davidecarlson** [comment]
That helps very much, thank you!

I do think there may be some problematic reads in the bottom sample, and I'll take a closer look at those.  Appreciate the help.
Best,
Dave
