### ISSUE TITLE
Disable long SV truncation

### ISSUE THREAD

**Issue by cathaloruaidh** [ryanlayer/samplot#162]
Hi,

Love the tool! I noticed that for long SVs, the display is often truncated in the middle, for example: 

![NA12878_3q29_DEL_original](https://user-images.githubusercontent.com/32680817/180240113-0b31f364-abac-4c36-a133-9ca92389e4ab.png)

Is there a way to disable this behaviour, or even change the threshold at which truncation occurs? I appreciate that this probably will make the plot hard to view, depending on the size/threshold. 

Thanks!
Cathal

**Comment by jbelyeu** [comment]
Hey Cathal, glad you're liking it. Check out the `--zoom` flag - what you're seeing is a figure that zooms in to show the flanks of the region of interest but doesn't include the whole region because it takes a long time to plot (and as you pointed out, can make viewing more difficult). If you increase the zoom arg from default of 500000 to say 2000000, it won't zoom in for this sv.

**Comment by cathaloruaidh** [comment]
Hey Jon, that work perfectly, thank you! Apologies for not reading the help more thoroughly!
