### ISSUE TITLE
plot whole chromosome

### ISSUE THREAD

**Issue by animesh** [ryanlayer/samplot#203]
trying to plot the whole chromosome for samples, for example putting "e" as the length of chromosome from https://www.ncbi.nlm.nih.gov/grc/human/data 
```
samplot plot  -b TK91L003.markdup.sorted.bam TK93L003.markdup.sorted.bam TK91L002.markdup.sorted.bam -o TK9N123del -c chr4 -s 0  -e 190214555 -t DEL
```
but unable to interpret the generated plot ![TK9N123del](https://github.com/user-attachments/assets/c3f8e9b7-d368-4122-8f43-840dc23bd83f) so i am guessing this is probably not the right way to approach this? Any suggestions how to achieve this? I would like to do this for all the chromosomes in the bam file, may be there is a script already for this?

**Comment by jbelyeu** [comment]
The axis labels are problematic but that may still be a versioning issue. Can you share the version of matplotlib you're using (`python -c "import matplotlib; print(matplotlib.__version__)"`)? 

As a more fundamental issue, samplot is not intended to support general whole-chromosome viewing. It's really intended to present evidence of specific individual structural variations identified via other software. The axes are dominated by the longest insert sizes in the viewing window, which for a whole chromosome is generally going to be from alignment noise rather than real breakpoints. Can you clarify what goals you're trying to achieve?

**Comment by animesh** [comment]
Thanks @jbelyeu for looking into this, looks like i have version 3.9.2?
```
python -c "import matplotlib; print(matplotlib.__version__)"
3.9.2
(samplot) 
```
yes, looks like this is probably not the right tool...what I want is to have an overview across the chromosome for multiple samples aligned to genome, would you suggest something else? like maybe use another tool to figure out the deleted regions in some samples and then input those into samplot instead?

**Comment by jbelyeu** [comment]
K, thanks for sharing that version, I'll take a better look at it as I can make time for it. If you'd like, you can try installing matplotlib version 3.6.3 which is working better for me.

Regarding the variant identification, I'd recommend starting with a dedicated structural variant calling tool to select regions of interest. The best choice for the job will depend a bit on the type of data and type of variation you're most interested in, but I'll take a guess that this is 2x150 Illumina WGS with a focus on large deletions. If that's the case I'd recommend starting by looking into Manta, CNVnator, and Lumpy.
